version: "3.8"
services:
    api:
      container_name: traxpense
      build: ./
      restart: always
      ports:
        - "8081:8081"
      depends_on:
        - mongo
    mongo:
      container_name: mongo
      image: mongo:latest
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
      restart: always
volumes:
  data:
