version: "3.8"
services:
    app:
      build:
        context: ./
        args:
          - PORT=${PORT}
          - MONGODB_URI=${MONGODB_URI}
          - PRIVATE_KEY={PRIVATE_KEY}
      restart: always
      ports:
        - "8081:8081"
      depends_on:
        - mongo
      env_file: .env.prod
    mongo:
      container_name: mongo
      image: mongo:latest
      volumes:
        - ~/traxpense-data:/data/db
      ports:
        - "27017:27017"
      restart: always
volumes:
  data:
