# This is a basic workflow to help you get started with Actions

name: Create A Multi Stage Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands to build and tag a docker image
      - name: Build and tag image
        run: docker build -t "docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/prod-deployment:$GITHUB_RUN_NUMBER"
        
      # Runs a set of commands for docker authentication / login
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      # Publish to github package repository / GPR
      - name: Publish to GPR
        run: docker push "docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/prod-deployment:$GITHUB_RUN_NUMBER"
        
      
